"""Model-agnostic REINFORCE-with-baseline training loop.

Same architectural rule as src/trainer.py: this module must not import anything
from qiskit. It touches `model` only through nn.Module (forward(),
parameters()) plus optional getattr() lookups for `lam` / `beta` that MAY exist,
purely for CSV logging. VQCPolicy and MLPPolicy share this loop unmodified, and
the optimizer -- with however many parameter groups the model calls for -- is
built by the caller (scripts/train_pg.py).

WHAT REPLACES WHAT, RELATIVE TO THE DQN LOOP

Gone: the replay buffer, the target network, the TD loss, and the epsilon
schedule. REINFORCE is on-policy, so experience cannot be replayed, and
exploration comes from sampling the policy rather than from a separate
epsilon knob -- for VQCPolicy the inverse temperature beta is itself trained,
so the agent anneals its own exploration.

Kept, deliberately: the vectorized environment, the per-episode CSV schema
(byte-compatible with the DQN one, see PG_CSV_HEADER), the 100-episode solve
window, the wall-clock budget, and the periodic greedy evaluation. Everything
in scripts/summarize.py and src/plots.py therefore reads a QPG run with no
changes at all.

ON-POLICY COLLECTION IS SYNCHRONIZED, NOT ROLLING

The obvious vectorized implementation collects episodes as they finish and fires
an update whenever N have completed. That quietly breaks the on-policy
assumption: at update time, other environments are mid-episode, and the steps
they already took came from an older policy: their log-probabilities no longer
correspond to the parameters being differentiated.

So collection here happens in synchronized *rounds*. All n_envs environments are
reset together, stepped until every one has terminated, and an environment that
finishes early is masked out rather than restarted. Rounds are accumulated until
`episodes_per_update` episodes are in hand, and no gradient step happens in the
middle of one. Every transition in a batch is therefore generated by exactly the
parameters the update differentiates.

The masked-out environments still sit in the batched forward and cost nothing
worth reclaiming: circuit simulation here is dispatch-bound, so a forward at
batch 8 costs about what batch 1 does (6.52 ms vs 6.81 ms, measured -- see
src/trainer.py::_select_actions_batched). Dropping them from the tensor would
save no wall-clock and would complicate the indexing.

WHY THE UPDATE RECOMPUTES LOG-PROBABILITIES

Action selection runs under no_grad and the update does a second forward over
the whole batch. Keeping the sampling-time graph instead would mean holding one
autograd graph per environment step and backpropagating through hundreds of
batch-1 circuit evaluations. Recomputing turns the entire batch into ONE
[T, n_qubits] forward through the torch-statevector backend, which is the same
reason the DQN side batches its replay sample. This is where policy gradient
happens to suit this backend better than Q-learning does: an episode's states
are a natural batch, so a 500-step episode costs roughly one forward, not 500.
"""

from __future__ import annotations

import csv
import os
import time
from collections import deque

import gymnasium as gym
import numpy as np
import torch
import torch.nn as nn

from qrl.trainers.evaluate import run_greedy_rollouts
from qrl.trainers.seeds import set_seed
from qrl.trainers.trainer_base import CSV_HEADER, _param_to_str

# The DQN header verbatim, plus two policy-gradient columns appended. Appending
# rather than substituting is what keeps scripts/summarize.py and src/plots.py
# working on QPG runs unchanged -- both index by column name, so extra trailing
# columns are invisible to them, while a renamed or reordered one would not be.
#
# `epsilon` is written empty for every row: PG has no exploration schedule, and
# writing 0.0 would draw a flat line on the epsilon axis that means something
# quite different from "no schedule exists". `w` is empty too, since a policy
# has no output-scaling weight -- _param_to_str returns "" for a missing
# attribute, so that falls out rather than being special-cased.
PG_CSV_HEADER = CSV_HEADER + ["entropy", "beta"]


def discounted_returns(rewards: list[float], gamma: float) -> np.ndarray:
    """Return-to-go G_t = sum_{k>=t} gamma^(k-t) r_k, computed backwards."""
    out = np.empty(len(rewards), dtype=np.float32)
    running = 0.0
    for t in range(len(rewards) - 1, -1, -1):
        running = rewards[t] + gamma * running
        out[t] = running
    return out


def _sample_actions(model: nn.Module, states: np.ndarray) -> np.ndarray:
    """Sample one action per state from pi(.|s) in ONE forward pass.

    no_grad: the update recomputes these logits (see the module docstring).
    """
    with torch.no_grad():
        logits = model(torch.as_tensor(states, dtype=torch.float32))
        probs = torch.softmax(logits, dim=-1)
        return torch.multinomial(probs, num_samples=1).squeeze(1).numpy()


def _beta_to_str(model: nn.Module) -> str:
    beta = getattr(model, "beta", None)
    if beta is None:
        return ""
    return f"{float(beta.detach().reshape(-1)[0]):.6f}"


def _collect_round(model, env, n_envs, seed, max_steps_per_episode) -> list[dict]:
    """One synchronized round: reset all envs, step until every one terminates.

    Returns one trajectory dict per environment. Environments that terminate
    early are masked out (`alive`) rather than restarted, so nothing generated
    after an episode boundary enters the batch. gymnasium 1.x autoresets the
    finished environment behind our back; masking is what makes that harmless.

    TERMINATION VS TRUNCATION IS RECORDED SEPARATELY, and this matters to any
    consumer that bootstraps a value estimate (src/a2c_trainer.py does; the
    REINFORCE loss does not and ignores these fields). CartPole ends an episode
    two quite different ways: the pole falls (`terminated` -- the true return
    from there is 0) or the 500-step limit is reached (`truncated` -- the pole is
    still up and the true return from there is large). Treating a truncation as
    terminal teaches a critic that the best states it ever reaches are worth
    nothing, which is precisely backwards on this environment, where a
    well-trained agent truncates EVERY episode.

    `final_state` is the observation the episode ended on, captured at the step
    where the environment finished -- gymnasium's next-step autoreset returns
    the true final observation there, and replaces it on the FOLLOWING step, so
    it is copied out at that moment rather than read afterwards.
    """
    obs, _info = env.reset(seed=[seed + i for i in range(n_envs)])
    states: list[list] = [[] for _ in range(n_envs)]
    actions: list[list] = [[] for _ in range(n_envs)]
    rewards: list[list] = [[] for _ in range(n_envs)]
    final_states: list = [None] * n_envs
    was_truncated = np.zeros(n_envs, dtype=bool)
    alive = np.ones(n_envs, dtype=bool)

    for _step in range(max_steps_per_episode):
        acts = _sample_actions(model, obs)
        next_obs, rews, terminated, truncated, _info = env.step(acts)
        dones = np.logical_or(terminated, truncated)

        for i in np.flatnonzero(alive):
            states[i].append(obs[i])
            actions[i].append(int(acts[i]))
            rewards[i].append(float(rews[i]))

        # Captured before `alive` is updated, and copied: next_obs is reused.
        for i in np.flatnonzero(alive & dones):
            final_states[i] = np.array(next_obs[i], dtype=np.float32)
            was_truncated[i] = bool(truncated[i])

        alive &= ~dones
        obs = next_obs
        if not alive.any():
            break

    # Any environment still alive never hit a done inside our own step cap, so
    # it is truncated by this function rather than by the environment.
    for i in np.flatnonzero(alive):
        final_states[i] = np.array(obs[i], dtype=np.float32)
        was_truncated[i] = True

    return [
        {"states": np.asarray(states[i], dtype=np.float32),
         "actions": np.asarray(actions[i], dtype=np.int64),
         "rewards": rewards[i],
         "final_state": final_states[i],
         "truncated": bool(was_truncated[i])}
        for i in range(n_envs)
    ]


def _policy_loss(model, batch, gamma, baseline, normalize_advantages, entropy_coef):
    """REINFORCE-with-baseline loss over a batch of complete episodes.

    Loss = -mean_t[ log pi(a_t|s_t) * A_t ] - entropy_coef * mean_t[ H(pi(.|s_t)) ]

    THE BASELINE IS NOT OPTIONAL IN PRACTICE. CartPole's rewards are all +1, so
    every return-to-go is positive and plain REINFORCE raises the probability of
    every action it ever took, including the ones that ended the episode. Only
    the *relative* size of the returns carries the learning signal, and
    subtracting the batch mean is what exposes it. Dividing by the batch
    standard deviation on top of that keeps the gradient scale roughly constant
    as episodes lengthen from ~20 steps to ~500, which otherwise changes the
    effective learning rate by an order of magnitude over a run.

    Subtracting a constant that does not depend on the action leaves the
    gradient unbiased; the scale division does bias it, in the usual and
    universally-used way -- it is a per-batch reparametrization of the step size.
    """
    states = torch.as_tensor(np.concatenate([ep["states"] for ep in batch]), dtype=torch.float32)
    actions = torch.as_tensor(np.concatenate([ep["actions"] for ep in batch]), dtype=torch.int64)
    returns = torch.as_tensor(
        np.concatenate([discounted_returns(ep["rewards"], gamma) for ep in batch]),
        dtype=torch.float32,
    )

    advantages = returns
    if baseline == "batch_mean":
        advantages = advantages - advantages.mean()
    elif baseline != "none":
        raise ValueError(f"unknown baseline {baseline!r}; expected 'batch_mean' or 'none'")
    if normalize_advantages:
        advantages = advantages / (advantages.std(unbiased=False) + 1e-8)

    # ONE forward for every state in the batch -- see the module docstring.
    logits = model(states)
    dist = torch.distributions.Categorical(logits=logits)
    log_probs = dist.log_prob(actions)
    entropy = dist.entropy()

    loss = -(log_probs * advantages).mean()
    if entropy_coef:
        loss = loss - entropy_coef * entropy.mean()
    return loss, float(entropy.mean().item())


def train_pg(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    results_path: str,
    checkpoint_path: str,
    seed: int,
    env_id: str = "CartPole-v1",
    max_episodes: int = 2000,
    gamma: float = 0.99,
    n_envs: int = 8,
    episodes_per_update: int = 8,  # rounded UP to a whole number of rounds
    baseline: str = "batch_mean",  # "batch_mean" | "none"
    normalize_advantages: bool = True,
    entropy_coef: float = 0.0,
    max_grad_norm: float | None = None,
    solve_threshold: float = 475.0,
    solve_window: int = 100,
    max_steps_per_episode: int = 500,
    max_wall_clock_s: float | None = None,
    eval_every: int = 50,
    eval_episodes: int = 5,
    eval_seed_base: int = 10_000,
    print_every: int = 10,
    verbose: bool = True,
) -> dict:
    """Run REINFORCE-with-baseline and write a per-episode CSV to results_path.

    Returns the same summary dict as src/trainer.py::train, so
    scripts/train_pg.py and scripts/sweep_seeds.py can consume either.

    Reproducibility works exactly as it does for the DQN loop: given the same
    seed this reproduces the same env resets and the same action samples, but
    the caller must ALSO seed model construction (scripts/train_pg.py does),
    since set_seed() here runs after `model` already exists.

    `episodes_per_update` is the batch size in episodes. It is rounded up to a
    whole number of n_envs-sized rounds, because a round is the smallest unit
    that can be collected without breaking the on-policy guarantee described in
    the module docstring; the value actually used is returned as
    `episodes_per_update`.
    """
    set_seed(seed)
    env = gym.vector.SyncVectorEnv([lambda: gym.make(env_id) for _ in range(n_envs)])

    rounds_per_update = max(1, -(-episodes_per_update // n_envs))  # ceil
    episodes_per_update = rounds_per_update * n_envs

    os.makedirs(os.path.dirname(results_path) or ".", exist_ok=True)

    total_env_steps = grad_steps = episode = 0
    reward_window: deque = deque(maxlen=solve_window)
    recent_losses: deque = deque(maxlen=50)
    solved_at_episode = solved_at_env_steps = solved_at_wall_clock = None
    last_eval_mean: float | None = None
    best_eval_mean = float("-inf")
    next_eval_at = eval_every
    last_entropy = ""
    stop = False

    start_time = time.time()

    with open(results_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(PG_CSV_HEADER)
        try:
            while episode < max_episodes and not stop:
                # --- collect a whole batch under one fixed set of parameters ---
                batch: list[dict] = []
                for _r in range(rounds_per_update):
                    batch.extend(
                        _collect_round(
                            model, env, n_envs,
                            seed=seed + 1000 * (grad_steps + 1) + 7 * _r,
                            max_steps_per_episode=max_steps_per_episode,
                        )
                    )

                # --- one gradient step on the batch ---
                loss, mean_entropy = _policy_loss(
                    model, batch, gamma, baseline, normalize_advantages, entropy_coef
                )
                optimizer.zero_grad()
                loss.backward()
                if max_grad_norm is not None:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
                optimizer.step()
                grad_steps += 1

                loss_value = loss.item()
                if np.isnan(loss_value):
                    raise RuntimeError(f"NaN loss at episode {episode}, grad step {grad_steps}")
                recent_losses.append(loss_value)
                last_entropy = f"{mean_entropy:.6f}"

                # --- one CSV row per episode in the batch ---
                for ep in batch:
                    ep_reward = float(sum(ep["rewards"]))
                    total_env_steps += len(ep["rewards"])
                    reward_window.append(ep_reward)
                    avg_reward_100 = sum(reward_window) / len(reward_window)
                    wall_clock_s = time.time() - start_time

                    eval_mean: float | str = ""
                    eval_std: float | str = ""
                    if eval_every and episode + 1 >= next_eval_at:
                        next_eval_at += eval_every
                        eval_t0 = time.time()
                        ev = run_greedy_rollouts(model, n_episodes=eval_episodes, env_id=env_id,
                                                 seed=eval_seed_base,
                                                 max_steps_per_episode=max_steps_per_episode)
                        eval_mean, eval_std = float(np.mean(ev)), float(np.std(ev))
                        last_eval_mean = eval_mean
                        best_eval_mean = max(best_eval_mean, eval_mean)
                        start_time += time.time() - eval_t0  # training-only clock

                    writer.writerow([
                        episode, total_env_steps, ep_reward, avg_reward_100,
                        "",  # epsilon: no exploration schedule under PG
                        (sum(recent_losses) / len(recent_losses)) if recent_losses else "",
                        wall_clock_s, grad_steps,
                        _param_to_str(model, "w"), _param_to_str(model, "lam"),
                        eval_mean, eval_std,
                        last_entropy, _beta_to_str(model),
                    ])
                    f.flush()

                    if verbose and (episode + 1) % print_every == 0:
                        note = f" | greedy {eval_mean:.1f}" if eval_mean != "" else ""
                        print(f"episode {episode + 1}/{max_episodes} | reward {ep_reward:.1f} | "
                              f"avg100 {avg_reward_100:.1f} | entropy {mean_entropy:.3f} | "
                              f"grad_steps {grad_steps} | wall_clock {wall_clock_s:.1f}s{note}")

                    episode += 1

                    if len(reward_window) == solve_window and avg_reward_100 >= solve_threshold:
                        solved_at_episode, solved_at_env_steps = episode, total_env_steps
                        solved_at_wall_clock = wall_clock_s
                        if verbose:
                            print(f"SOLVED at episode {episode} (avg100={avg_reward_100:.1f})")
                        stop = True
                        break
                    if episode >= max_episodes:
                        stop = True
                        break

                if not stop and max_wall_clock_s is not None and \
                        time.time() - start_time >= max_wall_clock_s:
                    if verbose:
                        print(f"stopping: max_wall_clock_s={max_wall_clock_s} reached")
                    stop = True
        finally:
            env.close()

    torch.save(model.state_dict(), checkpoint_path)

    return {
        "results_path": results_path,
        "checkpoint_path": checkpoint_path,
        "episodes_run": episode,
        "total_env_steps": total_env_steps,
        "grad_steps": grad_steps,
        "solved": solved_at_episode is not None,
        "episodes_to_solve": solved_at_episode,
        "env_steps_to_solve": solved_at_env_steps,
        "wall_clock_to_solve_s": solved_at_wall_clock,
        "last_eval_mean_reward": last_eval_mean,
        "best_eval_mean_reward": None if best_eval_mean == float("-inf") else best_eval_mean,
        "n_envs": n_envs,
        "episodes_per_update": episodes_per_update,
    }


if __name__ == "__main__":
    # discounted_returns against a hand-computed case: rewards all 1, gamma 0.9.
    got = discounted_returns([1.0, 1.0, 1.0], gamma=0.9)
    assert np.allclose(got, [1 + 0.9 + 0.81, 1 + 0.9, 1.0]), got

    # The baseline must centre the advantages, and normalization must scale them.
    from qrl.models.mlp import MLPPolicy

    set_seed(0)
    model = MLPPolicy()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    result = train_pg(
        model, optimizer, results_path="results/_pg_smoke.csv",
        checkpoint_path="results/_pg_smoke.pt", seed=0,
        max_episodes=16, n_envs=4, episodes_per_update=8, eval_every=0, verbose=False,
    )
    assert result["episodes_run"] == 16, result
    assert result["grad_steps"] == 2, result
    assert result["total_env_steps"] > 0, result
    assert result["episodes_per_update"] == 8, result

    import pandas as pd

    df = pd.read_csv("results/_pg_smoke.csv")
    assert list(df.columns) == PG_CSV_HEADER, df.columns
    assert len(df) == 16, len(df)
    # The columns summarize.py and plots.py read must be populated.
    for col in ("episode", "total_env_steps", "episode_reward", "avg_reward_100",
                "wall_clock_s", "grad_steps", "mean_loss"):
        assert df[col].notna().all(), f"{col} has gaps"
    assert df["epsilon"].isna().all(), "epsilon should be blank under PG"
    import os as _os
    _os.remove("results/_pg_smoke.csv")
    _os.remove("results/_pg_smoke.pt")
    print("pg_trainer.py smoke test OK")
