"""
PPO on QuantumSpinCartPole, as a policy-gradient counterpart to train_dqn.py.

Why PPO is worth trying here specifically: it is on-policy, so there is no replay
buffer. The history observation modes make the observation depend on the agent's
own past actions, which means a replay buffer fills with action-histories
generated by stale policies -- exactly the failure mode that made DQN's
full_hist worse than plain full. PPO regenerates its data every update, so that
problem does not arise.

Same observation modes, same evaluation protocol, and the same fixed eval seeds
(1000..) as train_dqn.py, so results drop straight into paired_compare.py.
Checkpoint selection uses a disjoint seed band (2000..) as train_dqn.py does.

Usage:
    python scripts/train_ppo.py --obs full      --noise-rabi 0.35 --seed 0
    python scripts/train_ppo.py --obs full_hist --noise-rabi 0.35 --seed 0
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

torch.set_num_threads(1)
sys.path.insert(0, str(Path(__file__).resolve().parent))

from quantum_spin_cartpole.constants import NOISE_RABI_RATIO  # noqa: E402
from greedy_baseline import sigma_for_noise_rabi  # noqa: E402
from train_dqn import N_ACTIONS, OBS_MODES, Featurizer, make_env  # noqa: E402


class ActorCritic(nn.Module):
    def __init__(self, dim: int, width: int = 128):
        super().__init__()
        self.body = nn.Sequential(
            nn.Linear(dim, width), nn.Tanh(),
            nn.Linear(width, width), nn.Tanh(),
        )
        self.pi = nn.Linear(width, N_ACTIONS)
        self.v = nn.Linear(width, 1)

    def forward(self, x):
        h = self.body(x)
        return self.pi(h), self.v(h).squeeze(-1)


@torch.no_grad()
def evaluate(net, feat: Featurizer, sigma, n_episodes=50, seed0=1000):
    """Deterministic (argmax) rollouts on fixed seeds."""
    env = make_env(sigma, seed=0)
    rets, lens, surv = [], [], []
    for k in range(n_episodes):
        obs, _ = env.reset(seed=seed0 + k)
        env._ou.reset(seed=seed0 + k)
        s = feat.reset(obs)
        total, steps = 0.0, 0
        term = trunc = False
        while not (term or trunc):
            logits, _ = net(torch.from_numpy(s).unsqueeze(0))
            a = int(logits.argmax(1).item())
            obs, r, term, trunc, _ = env.step(a)
            s = feat.step(obs, a)
            total += r
            steps += 1
        rets.append(total); lens.append(steps); surv.append(bool(trunc and not term))
    rets = np.array(rets)
    return {
        "return_mean": float(rets.mean()),
        "return_std": float(rets.std(ddof=1)) if len(rets) > 1 else 0.0,
        "return_median": float(np.median(rets)),
        "length_mean": float(np.mean(lens)),
        "survival_rate": float(np.mean(surv)),
        "returns": rets.tolist(),
    }


def train(args):
    sigma = args.sigma_ou if args.sigma_ou is not None else sigma_for_noise_rabi(args.noise_rabi)
    torch.manual_seed(args.seed)
    rng = np.random.default_rng(args.seed)

    feat = Featurizer(args.obs, hist=args.hist)
    eval_feat = Featurizer(args.obs, hist=args.hist)
    net = ActorCritic(feat.dim, args.width)
    opt = torch.optim.Adam(net.parameters(), lr=args.lr, eps=1e-5)

    env = make_env(sigma, seed=args.seed)
    ep_counter = 0
    train_seed0 = 700_000 + args.seed * 100_000
    obs, _ = env.reset(seed=train_seed0)
    env._ou.reset(seed=train_seed0)
    s = feat.reset(obs)

    ep_ret, train_rets = 0.0, []
    curve, best, best_state = [], {"return_mean": -1e9}, None
    t0 = time.time()
    n_updates = args.steps // args.rollout

    print(f"[PPO {args.obs} seed{args.seed}] dim {feat.dim}, sigma_ou {sigma:.5f} "
          f"(noise/Rabi {args.noise_rabi}), {args.steps} steps, {n_updates} updates")

    step = 0
    for update in range(1, n_updates + 1):
        S = np.zeros((args.rollout, feat.dim), dtype=np.float32)
        A = np.zeros(args.rollout, dtype=np.int64)
        LP = np.zeros(args.rollout, dtype=np.float32)
        R = np.zeros(args.rollout, dtype=np.float32)
        V = np.zeros(args.rollout, dtype=np.float32)
        DONE = np.zeros(args.rollout, dtype=np.float32)   # true termination only
        CUT = np.zeros(args.rollout, dtype=np.float32)    # episode boundary of any kind
        BOOT = np.zeros(args.rollout, dtype=np.float32)   # V(s') when truncated

        for t in range(args.rollout):
            st = torch.from_numpy(s).unsqueeze(0)
            with torch.no_grad():
                logits, v = net(st)
                dist = torch.distributions.Categorical(logits=logits)
                a = dist.sample()
                lp = dist.log_prob(a)
            a = int(a.item())

            obs, r, term, trunc, _ = env.step(a)
            s2 = feat.step(obs, a)

            S[t], A[t], LP[t], R[t], V[t] = s, a, float(lp), r, float(v)
            DONE[t] = float(term)
            CUT[t] = float(term or trunc)
            if trunc and not term:
                with torch.no_grad():
                    _, v2 = net(torch.from_numpy(s2).unsqueeze(0))
                BOOT[t] = float(v2)

            ep_ret += r
            s = s2
            step += 1

            if term or trunc:
                train_rets.append(ep_ret); ep_ret = 0.0
                ep_counter += 1
                obs, _ = env.reset(seed=train_seed0 + ep_counter)
                env._ou.reset(seed=train_seed0 + ep_counter)
                s = feat.reset(obs)

        with torch.no_grad():
            _, last_v = net(torch.from_numpy(s).unsqueeze(0))
        last_v = float(last_v)

        # GAE. On truncation the episode is cut but the future is not worthless,
        # so bootstrap from V(s'); on true termination the value really is 0.
        adv = np.zeros(args.rollout, dtype=np.float32)
        gae = 0.0
        for t in reversed(range(args.rollout)):
            if CUT[t]:
                next_v = BOOT[t]          # 0.0 unless truncated
                next_nonterminal = 0.0    # do not carry GAE across episodes
            else:
                next_v = V[t + 1] if t + 1 < args.rollout else last_v
                next_nonterminal = 1.0
            delta = R[t] + args.gamma * next_v * (1.0 - DONE[t]) - V[t]
            gae = delta + args.gamma * args.lam * next_nonterminal * gae
            adv[t] = gae
        ret = adv + V

        St = torch.from_numpy(S); At = torch.from_numpy(A)
        LPt = torch.from_numpy(LP); ADVt = torch.from_numpy(adv); RETt = torch.from_numpy(ret)
        ADVt = (ADVt - ADVt.mean()) / (ADVt.std() + 1e-8)

        idx = np.arange(args.rollout)
        for _ in range(args.epochs):
            rng.shuffle(idx)
            for k in range(0, args.rollout, args.minibatch):
                mb = idx[k:k + args.minibatch]
                logits, v = net(St[mb])
                dist = torch.distributions.Categorical(logits=logits)
                lp = dist.log_prob(At[mb])
                ratio = torch.exp(lp - LPt[mb])
                a1 = ratio * ADVt[mb]
                a2 = torch.clamp(ratio, 1 - args.clip, 1 + args.clip) * ADVt[mb]
                pi_loss = -torch.min(a1, a2).mean()
                v_loss = nn.functional.mse_loss(v, RETt[mb])
                ent = dist.entropy().mean()
                loss = pi_loss + args.vf_coef * v_loss - args.ent_coef * ent
                opt.zero_grad(); loss.backward()
                nn.utils.clip_grad_norm_(net.parameters(), 0.5)
                opt.step()

        if update % args.eval_every_updates == 0 or update == n_updates:
            ev = evaluate(net, eval_feat, sigma, n_episodes=args.eval_episodes,
                          seed0=args.select_seed0)
            recent = float(np.mean(train_rets[-20:])) if train_rets else float("nan")
            curve.append({"step": step, "train_recent20": recent,
                          **{k: v for k, v in ev.items() if k != "returns"}})
            print(f"  step {step:>7}  train20 {recent:>8.2f}  "
                  f"eval {ev['return_mean']:>8.2f} +- {ev['return_std']:<6.1f} "
                  f"len {ev['length_mean']:>6.1f}  surv {ev['survival_rate']*100:>3.0f}%")
            if ev["return_mean"] > best["return_mean"]:
                best = ev
                best_state = {k: v.clone() for k, v in net.state_dict().items()}

    if best_state is not None:
        net.load_state_dict(best_state)
    final = evaluate(net, eval_feat, sigma, n_episodes=args.final_episodes)
    elapsed = time.time() - t0
    print(f"  FINAL ({args.final_episodes} eps): {final['return_mean']:.2f} "
          f"+- {final['return_std']:.2f}  median {final['return_median']:.2f}  "
          f"len {final['length_mean']:.1f}  survive {final['survival_rate']*100:.0f}%")
    print(f"  {elapsed/60:.1f} min")

    out = Path(args.out or f"results/ppo_{args.obs}_nr{args.noise_rabi}_seed{args.seed}.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    if args.save_model:
        ckpt = out.with_suffix(".pt")
        torch.save({
            "algo": "ppo", "state_dict": net.state_dict(),
            "obs": args.obs, "input_dim": feat.dim, "hist": args.hist,
            "width": args.width, "noise_rabi": args.noise_rabi, "sigma_ou": sigma,
            "seed": args.seed, "steps": args.steps,
            "final": {k: v for k, v in final.items() if k != "returns"},
        }, ckpt)
        print(f"  saved {ckpt}")
    out.write_text(json.dumps({
        "algo": "ppo", "obs": args.obs, "seed": args.seed,
        "noise_rabi": args.noise_rabi, "sigma_ou": sigma, "input_dim": feat.dim,
        "steps": args.steps, "curve": curve, "final": final, "wall_clock_s": elapsed,
        "hparams": {k: v for k, v in vars(args).items() if k != "out"},
    }, indent=2))
    print(f"  wrote {out}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--obs", choices=OBS_MODES, default="full")
    p.add_argument("--hist", type=int, default=8)
    p.add_argument("--noise-rabi", type=float, default=NOISE_RABI_RATIO)
    p.add_argument("--sigma-ou", type=float, default=None)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--steps", type=int, default=150_000)
    p.add_argument("--width", type=int, default=128)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--gamma", type=float, default=0.99)
    p.add_argument("--lam", type=float, default=0.95)
    p.add_argument("--rollout", type=int, default=2048)
    p.add_argument("--minibatch", type=int, default=256)
    p.add_argument("--epochs", type=int, default=4)
    p.add_argument("--clip", type=float, default=0.2)
    p.add_argument("--vf-coef", type=float, default=0.5)
    p.add_argument("--ent-coef", type=float, default=0.01)
    p.add_argument("--eval-every-updates", type=int, default=5)
    p.add_argument("--eval-episodes", type=int, default=20)
    p.add_argument("--final-episodes", type=int, default=50)
    p.add_argument("--select-seed0", type=int, default=2000)
    p.add_argument("--save-model", action="store_true",
                   help="write the best checkpoint next to the results JSON")
    p.add_argument("--out", default=None)
    args = p.parse_args()
    train(args)


if __name__ == "__main__":
    main()
